spring:
  application:
    name: banggusuk_michelin

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:tokyo-flames-441110-n9-52d8ce97de12.json
        project-id: tokyo-flames-441110-n9
        bucket: banggusuk_michelin

  jwt:
    secret: secret

  jpa:
    hibernate:
      ddl-auto: create-drop  # option type: create, create-drop, update, validate, none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect  # 쿼리의 기준이 되는 데이터베이스 엔진을 설정합니다.
        show_sql: true  # sql 쿼리를 보여줍니다.
        format_sql: true  # sql query formatting
        use_sql_comments: true  # sql 쿼리의 추가정보를 보여줍니다.

  h2:
    console:
      enabled: true  # H2 Console을 사용할지 여부 (H2 Console은 H2 Database를 UI로 제공해주는 기능)
      path: /h2-console  # H2 Console의 Path
    # Database Setting Info (Database를 H2로 사용하기 위해 H2연결 정보 입력)
  datasource:
    driver-class-name: org.h2.Driver  # Database를 H2로 사용하겠다.
    url: jdbc:h2:~/test  # H2 접속 정보
    username: sa  # H2 접속 시 입력할 username 정보 (원하는 것으로 입력)
    password:  # H2 접속 시 입력할 password 정보 (원하는 것으로 입력)

kakao:
  key:
    client-id: 56834518a399e1ca8247d5f53449c20a
  redirect-uri: https://react-kakao-login-dkwic.run-ap-south1.goorm.site

